<?php

namespace Database\Seeders;

use App\Models\Finance\AccountBank;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $data = array(
        //     [
        //         'nama'          =>'Kas' ,
        //         'nomor'         =>'1-10001' ,
        //         'category'      => 3 ,
        //         'details'       =>'Kas Perusahaan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => 'Mandiri',
        //         'no_rekening'   => '23456789654',
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Kas Perusahaan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Rekening Bank' ,
        //         'nomor'         =>'1-10002' ,
        //         'category'      => 3 ,
        //         'details'       =>'Rekening Bank Perusahaan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => 'Mandiri',
        //         'no_rekening'   => '23456779654',
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Rekening Bank Perusahaan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Giro' ,
        //         'nomor'         =>'1-10003' ,
        //         'category'      => 3 ,
        //         'details'       =>'Giro' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => 'Mandiri',
        //         'no_rekening'   => '23456779654',
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Giro',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Piutang Usaha' ,
        //         'nomor'         =>'1-10101' ,
        //         'category'      => 1 ,
        //         'details'       =>'Akun Piutang Usaha' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Akun Piutang Usaha',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Piutang Belum Ditagih' ,
        //         'nomor'         =>'1-10102' ,
        //         'category'      => 1 ,
        //         'details'       =>'Akun Piutang Belum Ditagih' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Akun Piutang Belum Ditagih',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Persediaan Barang' ,
        //         'nomor'         =>'1-10201' ,
        //         'category'      => 4 ,
        //         'details'       =>'Akun Persediaan Barang' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Akun Persediaan Barang',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Biaya Dibayar Di Muka' ,
        //         'nomor'         =>'1-10301' ,
        //         'category'      => 2 ,
        //         'details'       =>'Biaya Dibayar Di Muka' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Biaya Dibayar Di Muka',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'PPN Masukan' ,
        //         'nomor'         =>'1-10302' ,
        //         'category'      => 2 ,
        //         'details'       =>'PPN Masukan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'PPN Masukan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Aset Tetap - Perlengkapan Kantor' ,
        //         'nomor'         =>'1-10701' ,
        //         'category'      => 5 ,
        //         'details'       =>'Aset Tetap - Perlengkapan Kantor' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL, 
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Aset Tetap - Perlengkapan Kantor',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Hutang Usaha' ,
        //         'nomor'         =>'2-20101' ,
        //         'category'      => 8 ,
        //         'details'       =>'Hutang Usaha' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Hutang Usaha',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Hutang Belum Ditagih' ,
        //         'nomor'         =>'2-20102' ,
        //         'category'      => 8 ,
        //         'details'       =>'Hutang Belum Ditagih' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Hutang Belum Ditagih',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Pendapatan Diterima Di Muka' ,
        //         'nomor'         =>'2-20201' ,
        //         'category'      => 10 ,
        //         'details'       =>'Pendapatan Diterima Di Muka' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Pendapatan Diterima Di Muka',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'PPN Keluaran' ,
        //         'nomor'         =>'2-20202' ,
        //         'category'      => 10 ,
        //         'details'       =>'PPN Keluaran' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'PPN Keluaran',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Ekuitas Saldo Awal' ,
        //         'nomor'         =>'3-30001' ,
        //         'category'      => 12 ,
        //         'details'       =>'Ekuitas Saldo Awal' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Ekuitas Saldo Awal',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Pendapatan Jasa' ,
        //         'nomor'         =>'4-40101' ,
        //         'category'      => 13 ,
        //         'details'       =>'Pendapatan Jasa' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Pendapatan Jasa',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Diskon Penjualan' ,
        //         'nomor'         =>'4-40102' ,
        //         'category'      => 13 ,
        //         'details'       =>'Diskon Penjualan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Diskon Penjualan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Retur Penjualan' ,
        //         'nomor'         =>'4-40103' ,
        //         'category'      => 13 ,
        //         'details'       =>'Retur Penjualan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Retur Penjualan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Pendapatan Belum Ditagih' ,
        //         'nomor'         =>'4-40104' ,
        //         'category'      => 13 ,
        //         'details'       =>'Pendapatan Belum Ditagih' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Pendapatan Belum Ditagih',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Beban Pokok Pendapatan' ,
        //         'nomor'         =>'5-50201' ,
        //         'category'      => 15 ,
        //         'details'       =>'Beban Pokok Pendapatan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Beban Pokok Pendapatan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Diskon Pembelian' ,
        //         'nomor'         =>'5-50202' ,
        //         'category'      => 15 ,
        //         'details'       =>'Diskon Pembelian' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Diskon Pembelian',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Pengiriman & Pengangkutan' ,
        //         'nomor'         =>'5-50203' ,
        //         'category'      => 15 ,
        //         'details'       =>'Pengiriman & Pengangkutan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Pengiriman & Pengangkutan',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Biaya Produksi' ,
        //         'nomor'         =>'5-50204' ,
        //         'category'      => 15 ,
        //         'details'       =>'Biaya Produksi' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Biaya Produksi',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Pengeluaran Barang Rusak' ,
        //         'nomor'         =>'6-60201' ,
        //         'category'      => 16 ,
        //         'details'       =>'Pengeluaran Barang Rusak' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Pengeluaran Barang Rusak',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Pendapatan Lain - lain' ,
        //         'nomor'         =>'7-70001' ,
        //         'category'      => 14 ,
        //         'details'       =>'Pendapatan Lain - lain' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Pendapatan Lain - lain',
        //         'status'        => 1
        //     ],
        //     [
        //         'nama'          =>'Penyesuaian Persediaan' ,
        //         'nomor'         =>'8-80001' ,
        //         'category'      => 17 ,
        //         'details'       =>'Penyesuaian Persediaan' ,
        //         'pajak_id'      => 1,
        //         'nama_bank'     => NULL,
        //         'no_rekening'   => NULL,
        //         'saldo'         => 0,
        //         'deskripsi'     => 'Penyesuaian Persediaan',
        //         'status'        => 1
        //     ],
        // );

        $data = array(
            array('nama' => 'Kas','nomor' => '1-10301','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 07:55:46','updated_at' => '2022-02-17 07:55:46','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Cash on Hand - IDR','nomor' => '1-10302','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '6000000','deskripsi' => '-','created_at' => '2022-02-17 08:37:33','updated_at' => '2022-02-23 03:37:06','debit' => NULL,'kredit' => NULL,'parent_account' => '1','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Bank','nomor' => '1-10304','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:40:58','updated_at' => '2022-02-17 08:46:36','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Cash in Bank BCA - IDR','nomor' => '1-10307','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:49:18','updated_at' => '2022-02-17 08:50:28','debit' => NULL,'kredit' => NULL,'parent_account' => '3','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Cash on Bank Mandiri - IDR','nomor' => '1-10309','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:50:03','updated_at' => '2022-02-17 08:51:26','debit' => NULL,'kredit' => NULL,'parent_account' => '3','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Cash in Bank BNI - IDR','nomor' => '1-10310','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:51:07','updated_at' => '2022-02-17 08:51:36','debit' => NULL,'kredit' => NULL,'parent_account' => '3','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Clearing Account','nomor' => '1-10311','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:52:05','updated_at' => '2022-02-17 08:52:05','debit' => NULL,'kredit' => NULL,'parent_account' => '3','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Piutang Usaha Pihak Ketiga','nomor' => '1-10313','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:52:42','updated_at' => '2022-02-17 08:53:29','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Piutang','nomor' => '1-10314','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:53:56','updated_at' => '2022-02-17 08:53:56','debit' => NULL,'kredit' => NULL,'parent_account' => '8','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Persediaan','nomor' => '1-10316','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:54:28','updated_at' => '2022-02-17 08:54:48','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Inventory','nomor' => '1-10317','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:55:25','updated_at' => '2022-02-17 08:55:25','debit' => NULL,'kredit' => NULL,'parent_account' => '10','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Beban Dibayar Dimuka','nomor' => '1-10319','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:56:01','updated_at' => '2022-02-17 08:56:50','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Uang Muka Sewa','nomor' => '1-10320','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:57:29','updated_at' => '2022-02-17 08:57:29','debit' => NULL,'kredit' => NULL,'parent_account' => '12','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Uang Muka Pembelian','nomor' => '1-10321','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:58:01','updated_at' => '2022-02-17 08:58:01','debit' => NULL,'kredit' => NULL,'parent_account' => '12','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Uang Muka Pajak - PPh 22','nomor' => '1-10322','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '-6000000','deskripsi' => '-','created_at' => '2022-02-17 08:58:35','updated_at' => '2022-02-23 03:37:06','debit' => NULL,'kredit' => NULL,'parent_account' => '12','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Uang Muka Pajak - PPh 23','nomor' => '1-10323','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:59:10','updated_at' => '2022-02-17 08:59:10','debit' => NULL,'kredit' => NULL,'parent_account' => '12','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Uang Muka Pajak - PPh 25','nomor' => '1-10324','category' => '2','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 08:59:52','updated_at' => '2022-02-17 08:59:52','debit' => NULL,'kredit' => NULL,'parent_account' => '12','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Fixed Asset','nomor' => '1-16001','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:11:45','updated_at' => '2022-02-17 09:12:34','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Fixed Asset','nomor' => '1-16002','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:13:19','updated_at' => '2022-02-17 09:13:19','debit' => NULL,'kredit' => NULL,'parent_account' => '18','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Tanah dan Bangunan','nomor' => '1-16004','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:21:14','updated_at' => '2022-02-17 09:21:42','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Tanah','nomor' => '1-16005','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:22:48','updated_at' => '2022-02-17 09:22:48','debit' => NULL,'kredit' => NULL,'parent_account' => '20','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Bangunan','nomor' => '1-16006','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:23:20','updated_at' => '2022-02-17 09:23:20','debit' => NULL,'kredit' => NULL,'parent_account' => '20','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Aktiva Tetap Lainnya','nomor' => '1-16008','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:24:03','updated_at' => '2022-02-17 09:24:24','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Kendaraan','nomor' => '1-16009','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:24:53','updated_at' => '2022-02-17 09:24:53','debit' => NULL,'kredit' => NULL,'parent_account' => '23','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Inventaris Kantor','nomor' => '1-16010','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:25:29','updated_at' => '2022-02-17 09:25:29','debit' => NULL,'kredit' => NULL,'parent_account' => '23','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Akumulasi Penyusutan','nomor' => '1-16012','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:26:27','updated_at' => '2022-02-17 09:26:37','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Ac. Depreciation','nomor' => '1-16013','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:27:13','updated_at' => '2022-02-17 09:27:13','debit' => NULL,'kredit' => NULL,'parent_account' => '26','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Ak. Penyusutan Bangunan','nomor' => '1-16014','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:27:44','updated_at' => '2022-02-17 09:27:44','debit' => NULL,'kredit' => NULL,'parent_account' => '26','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Ak. Penyusutan Kendaraan','nomor' => '1-16015','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:28:14','updated_at' => '2022-02-17 09:28:14','debit' => NULL,'kredit' => NULL,'parent_account' => '26','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Ak. Penyusutan Inventaris','nomor' => '1-16016','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:28:43','updated_at' => '2022-02-17 09:28:43','debit' => NULL,'kredit' => NULL,'parent_account' => '26','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Aktiva Tidak Lancar Lainnya','nomor' => '1-16018','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:29:23','updated_at' => '2022-02-17 09:29:33','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Others Assets','nomor' => '1-16019','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:29:59','updated_at' => '2022-02-17 09:29:59','debit' => NULL,'kredit' => NULL,'parent_account' => '31','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Investasi Jangka Panjang','nomor' => '1-16021','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:30:36','updated_at' => '2022-02-17 09:30:47','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Investment','nomor' => '1-16022','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:31:14','updated_at' => '2022-02-17 09:31:14','debit' => NULL,'kredit' => NULL,'parent_account' => '33','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Aktiva Pajak Tangguhan','nomor' => '1-16024','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:31:48','updated_at' => '2022-02-17 09:32:05','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Deffered Tax','nomor' => '1-16025','category' => '18','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:32:56','updated_at' => '2022-02-17 09:32:56','debit' => NULL,'kredit' => NULL,'parent_account' => '35','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang Usaha Pihak Ketiga','nomor' => '2-20202','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:33:42','updated_at' => '2022-02-17 09:33:53','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang','nomor' => '2-20203','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:34:28','updated_at' => '2022-02-17 09:34:28','debit' => NULL,'kredit' => NULL,'parent_account' => '37','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Kewajiban Lancar Lainnya','nomor' => '2-20205','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:35:53','updated_at' => '2022-02-17 09:36:05','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Customer Deposit','nomor' => '2-20206','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:36:41','updated_at' => '2022-02-17 09:36:41','debit' => NULL,'kredit' => NULL,'parent_account' => '39','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang Bank','nomor' => '2-20208','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:37:11','updated_at' => '2022-02-17 09:37:21','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Bank Loan','nomor' => '2-20209','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:37:44','updated_at' => '2022-02-17 09:37:44','debit' => NULL,'kredit' => NULL,'parent_account' => '41','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang Pajak','nomor' => '2-20211','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:38:24','updated_at' => '2022-02-17 09:38:38','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'AP Tax','nomor' => '2-20212','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:39:22','updated_at' => '2022-02-17 09:39:22','debit' => NULL,'kredit' => NULL,'parent_account' => '43','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang PPh 21','nomor' => '2-20213','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:40:13','updated_at' => '2022-02-17 09:40:13','debit' => NULL,'kredit' => NULL,'parent_account' => '43','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang PPh 21','nomor' => '2-20214','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:40:16','updated_at' => '2022-02-17 09:40:16','debit' => NULL,'kredit' => NULL,'parent_account' => '43','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang PPN','nomor' => '2-20215','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:40:43','updated_at' => '2022-02-17 09:40:43','debit' => NULL,'kredit' => NULL,'parent_account' => '43','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang PPh 25','nomor' => '2-20216','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:41:23','updated_at' => '2022-02-17 09:41:23','debit' => NULL,'kredit' => NULL,'parent_account' => '43','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Yang Masih Harus Dibayar','nomor' => '2-20218','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:42:27','updated_at' => '2022-02-17 09:49:06','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Accruals','nomor' => '2-20219','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:49:44','updated_at' => '2022-02-17 09:49:44','debit' => NULL,'kredit' => NULL,'parent_account' => '49','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Accrued Gaji','nomor' => '2-20220','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:50:18','updated_at' => '2022-02-17 09:50:18','debit' => NULL,'kredit' => NULL,'parent_account' => '49','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Accrued Listrik','nomor' => '2-20221','category' => '10','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:50:51','updated_at' => '2022-02-17 09:50:51','debit' => NULL,'kredit' => NULL,'parent_account' => '49','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Hutang Usaha Jangka Panjang Inter Co.','nomor' => '2-23001','category' => '19','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:54:21','updated_at' => '2022-02-17 09:54:31','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Share Holder Loan','nomor' => '2-23002','category' => '19','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:55:17','updated_at' => '2022-02-17 09:55:17','debit' => NULL,'kredit' => NULL,'parent_account' => '53','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Modal Saham','nomor' => '3-30002','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:56:15','updated_at' => '2022-02-17 09:56:26','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Equity','nomor' => '3-30003','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:57:01','updated_at' => '2022-02-17 09:57:01','debit' => NULL,'kredit' => NULL,'parent_account' => '55','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Setoran Modal Pusat','nomor' => '3-30004','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:57:32','updated_at' => '2022-02-17 09:57:32','debit' => NULL,'kredit' => NULL,'parent_account' => '55','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Penarikan Modal','nomor' => '3-30006','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:58:03','updated_at' => '2022-02-17 09:58:13','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Penarikan Saham','nomor' => '3-30007','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:58:49','updated_at' => '2022-02-17 09:58:49','debit' => NULL,'kredit' => NULL,'parent_account' => '1','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Dividen','nomor' => '3-30009','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 09:59:57','updated_at' => '2022-02-17 10:00:08','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Dividen Paid','nomor' => '3-30010','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:04:23','updated_at' => '2022-02-17 10:04:23','debit' => NULL,'kredit' => NULL,'parent_account' => '60','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Laba Ditahan Tahun Tahun Sebelumnya','nomor' => '3-30012','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:05:33','updated_at' => '2022-02-17 10:05:44','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Retained Earning','nomor' => '3-30013','category' => '12','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:06:23','updated_at' => '2022-02-17 10:06:23','debit' => NULL,'kredit' => NULL,'parent_account' => '62','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Penjualan Barang','nomor' => '4-40102','category' => '13','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:07:23','updated_at' => '2022-02-17 10:07:59','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Sales','nomor' => '4-40103','category' => '13','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:08:33','updated_at' => '2022-02-17 10:08:33','debit' => NULL,'kredit' => NULL,'parent_account' => '64','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Sales Discount','nomor' => '4-40104','category' => '13','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:09:08','updated_at' => '2022-02-17 10:09:08','debit' => NULL,'kredit' => NULL,'parent_account' => '64','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Sales Return','nomor' => '4-40105','category' => '13','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:09:41','updated_at' => '2022-02-17 10:09:41','debit' => NULL,'kredit' => NULL,'parent_account' => '64','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pendapatan Jasa','nomor' => '4-40107','category' => '13','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:10:15','updated_at' => '2022-02-17 10:10:27','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pendapatan Jasa','nomor' => '4-40108','category' => '13','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:11:05','updated_at' => '2022-02-17 10:11:05','debit' => NULL,'kredit' => NULL,'parent_account' => '68','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pembelian','nomor' => '5-50202','category' => '15','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:11:45','updated_at' => '2022-02-17 10:11:55','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pembelian','nomor' => '5-50203','category' => '15','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:12:23','updated_at' => '2022-02-17 10:12:23','debit' => NULL,'kredit' => NULL,'parent_account' => '70','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Kas Jalan','nomor' => '5-50204','category' => '15','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:12:44','updated_at' => '2022-02-17 10:12:44','debit' => NULL,'kredit' => NULL,'parent_account' => '70','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Penyesuaian Saldo Persediaan','nomor' => '5-50206','category' => '15','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:13:21','updated_at' => '2022-02-17 10:13:30','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Penyesuaian Saldo Persediaan','nomor' => '5-50207','category' => '15','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:13:55','updated_at' => '2022-02-17 10:13:55','debit' => NULL,'kredit' => NULL,'parent_account' => '73','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Gaji dan Upah','nomor' => '6-60202','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:14:55','updated_at' => '2022-02-17 10:15:19','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Salary','nomor' => '6-60203','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:15:40','updated_at' => '2022-02-17 10:15:40','debit' => NULL,'kredit' => NULL,'parent_account' => '75','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Bonus & THR','nomor' => '6-60204','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:16:35','updated_at' => '2022-02-17 10:16:35','debit' => NULL,'kredit' => NULL,'parent_account' => '75','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Overtime','nomor' => '6-60205','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:17:00','updated_at' => '2022-02-17 10:17:00','debit' => NULL,'kredit' => NULL,'parent_account' => '75','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Food & Transport','nomor' => '6-60206','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:17:30','updated_at' => '2022-02-17 10:17:30','debit' => NULL,'kredit' => NULL,'parent_account' => '75','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Medical','nomor' => '6-60207','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:17:55','updated_at' => '2022-02-17 10:17:55','debit' => NULL,'kredit' => NULL,'parent_account' => '75','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Tunjangan PPh 21','nomor' => '6-60208','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:18:41','updated_at' => '2022-02-17 10:18:41','debit' => NULL,'kredit' => NULL,'parent_account' => '75','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Kantol','nomor' => '6-60215','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:19:36','updated_at' => '2022-02-17 10:23:30','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Office Expenses','nomor' => '6-60211','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:20:24','updated_at' => '2022-02-17 10:20:24','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Electricity','nomor' => '6-60212','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:21:11','updated_at' => '2022-02-17 10:21:11','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Telephone, Fax, E-Mail','nomor' => '6-60213','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:21:49','updated_at' => '2022-02-17 10:21:49','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Printing, Stationary','nomor' => '6-60214','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:23:09','updated_at' => '2022-02-17 10:23:09','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pos & Materai','nomor' => '6-60216','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:24:34','updated_at' => '2022-02-17 10:24:34','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Traveling','nomor' => '6-60217','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:25:04','updated_at' => '2022-02-17 10:25:04','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Office Rental','nomor' => '6-60218','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:25:41','updated_at' => '2022-02-17 10:25:41','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Office Facilities','nomor' => '6-60219','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:26:15','updated_at' => '2022-02-17 10:26:15','debit' => NULL,'kredit' => NULL,'parent_account' => '82','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Pemasaran','nomor' => '6-60221','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:36:19','updated_at' => '2022-02-17 10:36:30','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Selling & Distribution','nomor' => '6-60222','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:37:04','updated_at' => '2022-02-17 10:37:04','debit' => NULL,'kredit' => NULL,'parent_account' => '91','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Freight','nomor' => '6-60223','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:39:02','updated_at' => '2022-02-17 10:39:02','debit' => NULL,'kredit' => NULL,'parent_account' => '91','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Sample','nomor' => '6-60224','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:39:39','updated_at' => '2022-02-17 10:39:39','debit' => NULL,'kredit' => NULL,'parent_account' => '91','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'advertising','nomor' => '6-60225','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:41:40','updated_at' => '2022-02-17 10:41:40','debit' => NULL,'kredit' => NULL,'parent_account' => '91','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Komisi Penjualan','nomor' => '6-60226','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:42:21','updated_at' => '2022-02-17 10:42:21','debit' => NULL,'kredit' => NULL,'parent_account' => '91','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Perbaikan','nomor' => '6-60228','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:43:07','updated_at' => '2022-02-17 10:43:25','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Maintenance Expenses','nomor' => '6-60229','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:43:56','updated_at' => '2022-02-17 10:43:56','debit' => NULL,'kredit' => NULL,'parent_account' => '97','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Fuel, Oil, Parking','nomor' => '6-60230','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:44:31','updated_at' => '2022-02-17 10:44:31','debit' => NULL,'kredit' => NULL,'parent_account' => '97','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Penyusutan','nomor' => '6-60232','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:45:17','updated_at' => '2022-02-17 10:45:32','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Depreciation Expenses','nomor' => '6-60233','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:46:08','updated_at' => '2022-02-17 10:46:08','debit' => NULL,'kredit' => NULL,'parent_account' => '100','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Dep Building','nomor' => '6-60234','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:46:38','updated_at' => '2022-02-17 10:46:38','debit' => NULL,'kredit' => NULL,'parent_account' => '100','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Dep Machinary','nomor' => '6-60235','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:47:14','updated_at' => '2022-02-17 10:47:14','debit' => NULL,'kredit' => NULL,'parent_account' => '100','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Dep Office Equipment','nomor' => '6-60236','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:47:45','updated_at' => '2022-02-17 10:47:45','debit' => NULL,'kredit' => NULL,'parent_account' => '100','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Operasional Lainnya','nomor' => '6-60238','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:48:27','updated_at' => '2022-02-17 10:48:39','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'General Expenses','nomor' => '6-60239','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:49:34','updated_at' => '2022-02-17 10:49:34','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Insurance','nomor' => '6-60240','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:50:21','updated_at' => '2022-02-17 10:50:21','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Donation','nomor' => '6-60241','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:50:51','updated_at' => '2022-02-17 10:50:51','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Entertainment','nomor' => '6-60242','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:51:25','updated_at' => '2022-02-17 10:51:25','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Bank Charges','nomor' => '6-60243','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:52:18','updated_at' => '2022-02-17 10:52:18','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Others Expenses','nomor' => '6-60244','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:52:42','updated_at' => '2022-02-17 10:52:42','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Licences','nomor' => '6-60245','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:53:10','updated_at' => '2022-02-17 10:53:10','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Manajemen Fee','nomor' => '6-60246','category' => '16','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:53:33','updated_at' => '2022-02-17 10:53:33','debit' => NULL,'kredit' => NULL,'parent_account' => '105','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pendapatan Lain-Lain','nomor' => '7-70002','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:54:05','updated_at' => '2022-02-17 10:54:37','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Others Income','nomor' => '7-70003','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:55:02','updated_at' => '2022-02-17 10:55:02','debit' => NULL,'kredit' => NULL,'parent_account' => '114','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Interest Income Deposit','nomor' => '7-70004','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:55:38','updated_at' => '2022-02-17 10:55:38','debit' => NULL,'kredit' => NULL,'parent_account' => '114','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Biaya Lain-Lain','nomor' => '7-70006','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:56:24','updated_at' => '2022-02-17 10:56:35','debit' => NULL,'kredit' => NULL,'parent_account' => NULL,'status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Pajak Jasaa Giro','nomor' => '7-70007','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:57:09','updated_at' => '2022-02-17 10:57:09','debit' => NULL,'kredit' => NULL,'parent_account' => '117','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Interest Expenses','nomor' => '7-70008','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:57:41','updated_at' => '2022-02-17 10:57:41','debit' => NULL,'kredit' => NULL,'parent_account' => '117','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Tax Pinalty','nomor' => '7-70009','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 10:58:07','updated_at' => '2022-02-17 10:58:07','debit' => NULL,'kredit' => NULL,'parent_account' => '117','status' => '0', 'creat_by_company' => '1'),
            array('nama' => 'Rounding','nomor' => '7-70010','category' => '14','details' => '-','pajak_id' => '1','nama_bank' => NULL,'no_rekening' => NULL,'saldo' => '0','deskripsi' => '-','created_at' => '2022-02-17 11:00:58','updated_at' => '2022-02-17 11:00:58','debit' => NULL,'kredit' => NULL,'parent_account' => '117','status' => '0', 'creat_by_company' => '1')
          );

        foreach ($data as $d) {
            AccountBank::create([
                'nama'          =>$d['nama'] ,
                'nomor'         =>$d['nomor'] ,
                'category'      =>$d['category'] ,
                'details'       =>$d['details'] ,
                'pajak_id'      =>$d['pajak_id'] ,
                'nama_bank'     =>$d['nama_bank'] ,
                'no_rekening'   =>$d['no_rekening'] ,
                'saldo'         =>$d['saldo'],
                'deskripsi'     =>$d['deskripsi'],
                'debit'         =>$d['debit'],
                'kredit'        =>$d['kredit'],
                'parent_account'=>$d['parent_account'],
                'status'        =>$d['status'],
                'creat_by_company'     => $d['creat_by_company']
            ]);
        }
    }
}
